<a href="https://colab.research.google.com/github/akdubey/AKDU/blob/main/Lecture_5c_Numpy_II_Re_shaping%2C_Rotation%2C_Cropping%2C_Joining_and_Splitting_of_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Topics to be covered

* Re-shaping of array
* Transposing Arrays
* Rotation of array
* Joining of arrays
* Splitting of arrays
* Data Types for ndarrays
* Arithmetic with NumPy Arrays


# Importing Numpy Package

In [1]:
import numpy as np

# Reshaping of Arrays

> * Reshaping means changing the shape of an array.
* For example, if you want to put the numbers 1 through 9 in a 3×3 grid

In [2]:
# Reshape the numbers 1 through 9 in a 3×3 grid (Enter valid dimension)
# e.g. for 9 elements dimension should be 3X3 or 1X9 or 9X1 
n = np.arange(1,10)
n.reshape((3,3))


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Check it Returns a Copy or View?

In [3]:
#Check if the returned array is a copy or a view:
n = np.arange(1,10)
n.reshape((3,3)).base   


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### The example above returns the original array, so it is a view.

# Flattening the arrays

> Converting a multidimensional array into a 1D array.

In [4]:
x = np.random.randint(10,size=(2,3))
print(x)
x.reshape(-1)

[[7 8 7]
 [9 6 9]]


array([7, 8, 7, 9, 6, 9])

# Transposing Arrays
Transposing is a special form of reshaping that similarly returns a view on the underlying data without copying anything

In [5]:
x = np.arange(1,10).reshape(3,3)
print(x)
x.T

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Rotation of Array

#### The rot90() function is used to rotate an array by 90 degrees in the plane specified by axes

#### Syntax - 
        numpy.rot90(m, k=1, axes=(0, 1))
        * m	Array of two or more dimensions.
        * k	Number of times the array is rotated by 90 degrees
        * axes	The array is rotated in the plane defined by the axes.

In [6]:
m = np.array([[1,2], [3,4], [5,6]])
m

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np.rot90(m)

array([[2, 4, 6],
       [1, 3, 5]])

In [8]:
np.rot90(m,2)

array([[6, 5],
       [4, 3],
       [2, 1]])

# Joining of Array

#### Joining means putting contents of two or more arrays in a single array.

  > * np.concatenate
* np.vstack
* np.hstack

   #### * We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. 
   #### * If axis is not explicitly passed, it is taken as 0.


# Axis in numpy array

In [9]:
# np.concatenate
x = np.array([1,2,3])
y = np.array([4,3,2])
np.concatenate([x,y])

array([1, 2, 3, 4, 3, 2])

# Joining 2D arrays

In [10]:
# If axis is not explicitly passed, it is taken as 0
x = np.array([[1,1,1],[2,2,2]])
y = np.array([[4,4,4],[5,5,5]])
np.concatenate([x,y]) 

array([[1, 1, 1],
       [2, 2, 2],
       [4, 4, 4],
       [5, 5, 5]])

In [11]:
# when axis =1
x = np.array([[1,1,1],[2,2,2]])
y = np.array([[4,4,4],[5,5,5]])
np.concatenate([x,y],axis=1) 

array([[1, 1, 1, 4, 4, 4],
       [2, 2, 2, 5, 5, 5]])

# Some Error

In [12]:
# when we have different dimension (e.g. 3X3 and 2X3 ) then 
x = np.array([[1,1,1],[2,2,2],[3,3,3]])
y = np.array([[4,4,4],[5,5,5]])
np.concatenate([x,y],axis=1) 

ValueError: ignored

In [13]:
x = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
y = np.array([[4,4,4],[5,5,5]])
np.concatenate([x,y],axis=0) 

ValueError: ignored

# np.vstack

#### allows us to concatenate two multi-dimensional arrays vertically 

In [14]:
x = np.array([[1,1,1],[2,2,2],[3,3,3]])
y = np.array([[4,4,4],[5,5,5]])
np.vstack([x,y])

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

# np.hstack

In [15]:
x = np.array([[1,1,1],[2,2,2]])
y = np.array([[4,4,4],[5,5,5]])
np.hstack([x,y])

array([[1, 1, 1, 4, 4, 4],
       [2, 2, 2, 5, 5, 5]])

# Splitting of arrays

#### The opposite of concatenation is splitting, which is implemented by the functions
> * np.split
* np.hsplit
* np.vsplit.


# np.split

The return value of the split() method is an array containing each of the split as an array.

> numpy.split(ary, indices_or_sections, axis=0)

Ref - https://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html


In [17]:
x = np.arange(1,10)
np.split(x,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [18]:
# Split [0:3] , [3:5] ,[5:7] and [7:]
x = np.arange(1,10)
np.split(x,[3,5,7])

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

# numpy.hsplit

Split an array into multiple sub-arrays horizontally (column-wise).

> numpy.hsplit(ary, indices_or_sections)

Ref - https://docs.scipy.org/doc/numpy/reference/generated/numpy.hsplit.html#numpy.hsplit

In [19]:
x = np.arange(1,10).reshape([3,3])
np.hsplit(x,3)

[array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]]), array([[3],
        [6],
        [9]])]

In [20]:
x = np.arange(1,11).reshape([2,5])
print(x)
np.hsplit(x,[2,5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[array([[1, 2],
        [6, 7]]), array([[ 3,  4,  5],
        [ 8,  9, 10]]), array([], shape=(2, 0), dtype=int64)]

# numpy.vsplit

Split an array into multiple sub-arrays vertically ( row-wise)

> numpy.vsplit(ary, indices_or_sections)

https://docs.scipy.org/doc/numpy/reference/generated/numpy.vsplit.html#numpy.vsplit

In [21]:
x = np.arange(1,11).reshape([5,2])
print(x)
np.vsplit(x,[3])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


[array([[1, 2],
        [3, 4],
        [5, 6]]), array([[ 7,  8],
        [ 9, 10]])]

# Data Types for ndarrays

* Don’t worry about memorizing the NumPy dtypes. 
It’s often only necessary to care about the general kind of data you’re dealing with, whether floating point, complex,
integer, boolean, string, or general Python object.

In [22]:
x = np.array([1,2,3,4])
x.dtype

dtype('int64')

In [23]:
x =np.array([1.2,2.3,4.3])
x.dtype

dtype('float64')

In [24]:
x = np.array(['1.2','23.3','4.5'],dtype=np.string_)
x.dtype

dtype('S4')

# Casting

In [25]:
#In this example, integers were cast to floating point.
x = np.array([1,2,3,4])
y= x.astype(np.float64)
y

array([1., 2., 3., 4.])

In [26]:
#casting floating-point numbers to be of integer dtype,
#the decimal part will be truncated
x =np.array([1.2,2.3,4.3])

y = x.astype(np.int32)
y

array([1, 2, 4], dtype=int32)

In [27]:
# you can use astype to convert an array of strings representing numbers
#to numeric form
x = np.array(['1.2','23.3','4.5'],dtype=np.string_)

y = x.astype(np.float)
y

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


array([ 1.2, 23.3,  4.5])

# Arithmetic with NumPy Arrays

> * Arrays are important because they enable you to express batch operations on data without writing any for loops.
* NumPy users call this vectorization
* Any arithmetic operations between equal-size arrays applies the operation element-wise.

In [28]:
# Multiplication
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,2,2],[3,3,3]])
x*y


array([[ 2,  4,  6],
       [12, 15, 18]])

In [29]:
# Subtraction
x-y

array([[-1,  0,  1],
       [ 1,  2,  3]])

In [30]:
1/x

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [31]:
x*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [32]:
x**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [33]:
# Comparisons between arrays of the same size yield boolean arrays
x>y

array([[False, False,  True],
       [ True,  True,  True]])