<a href="https://colab.research.google.com/github/akdubey/AKDU/blob/main/Lecture_5b_Numpy_III_Universal_Functions%2C_Searching%2C_Sorting%2C_Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Topics to be covered

* Universal Functions
* Searching
* Sorting
* Filtering


# Importing Numpy Package

In [1]:
import numpy as np

# Computation on NumPy arrays
 * #### Computation on NumPy arrays can be very fast, or it can be very slow.
 
 * #### The key to making it fast is to use vectorized operations, generally implemented through NumPy’s universal functions (ufuncs).

# What is Vectorization?

Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

# Array arithmetic

# Absolute value

In [2]:
x = np.array([-2,-1,0,1,2])
np.absolute(x)

array([2, 1, 0, 1, 2])

# Exponents and logarithms

In [3]:
# e^x
x = [1,2,3]
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [4]:
#2^x
x=[1,2,3]
np.exp2(x)

array([2., 4., 8.])

In [5]:
# ln(x)
x=[1,2,3]
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [6]:
np.log2(x)

array([0.       , 1.       , 1.5849625])

In [7]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125])

# Advanced Ufunc Features

# 1. Specifying output

For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored.

In [8]:
# Example
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)

array([ 0., 10., 20., 30., 40.])

#### if we write y = x*10 then , It create a temporary array to hold the results of x*10 , followed by a second operation copying those values into the y array

# 2. Aggregations (Reduce method)

* #### if you like to reduce an array with a particular operation, we can use the reduce method of any ufunc. 

* #### A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

In [9]:
# alling reduce on the add ufunc returns the sum of all elements in the
#array
x = np.arange(1,11)
np.add.reduce(x)

55

In [10]:
# If you like to store all intermidiate results of the computation the we can
# use accumlate().

np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

# Note - there are dedicated NumPy functions to compute the results 

* np.sum
* np.prod
* np.cumsum
* np.cumprod


# Aggregation functions available in NumPy

* #### Often when you are faced with a large amount of data, a first step is to compute summary statistics for the data in question.

* #### numpy provides following Aggregation function

In [11]:
x = np.arange(1,101).reshape(10,10)
print(x)
x[:,[1]]

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52],
       [62],
       [72],
       [82],
       [92]])

In [12]:
print(" Sum of Elements ",np.sum(x[:,[1]]))
print(" Product of Elements ",np.prod(x[:,[1]]))
print(" Mean of Elements ",np.mean(x[:,[1]]))
#Standard deviation is a number used to tell how measurements for a group 
# are spread out from the average (mean), or expected value
print(" Standard deviation ",np.std(x[:,[1]])) 
print(" Minimum Value ",np.min(x[:,[1]]))
print(" Maximum Value ",np.max(x[:,[1]])) 
print(" Meadian ",np.median(x[:,[1]]))
print("ANy elemet are True : ",np.any(x[:,[1]]))

 Sum of Elements  470
 Product of Elements  1242688846823424
 Mean of Elements  47.0
 Standard deviation  28.722813232690143
 Minimum Value  2
 Maximum Value  92
 Meadian  47.0
ANy elemet are True :  True


In [13]:
# Working with nan
x = np.array([1,2,3,4,5,np.nan,6,7,8,9])
np.nanmean(x)

5.0

In [14]:
x = np.array([1,2,3,'',4,5])
def m(x):
    if x == '':
        return np.nan
    else:
        return float(x)
y = np.frompyfunc(m,1,1)
x = y(x).astype(float)
np.nanmean(x)

3.0

# How To Create Your Own ufunc

#### To create you own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

> The frompyfunc() method takes the following arguments:
* function - the name of the function.
* inputs - the number of input arguments (arrays).
* outputs - the number of output arrays.

In [15]:
# Create a ufunc which return cube of a given number

def myufunc(x):
    return x**3

In [16]:
x = np.arange(1,11)
cube = np.frompyfunc(myufunc,1,1)
cube(x)

array([1, 8, 27, 64, 125, 216, 343, 512, 729, 1000], dtype=object)

In [17]:
# Check if a Function is a ufunc
type(cube)

numpy.ufunc

In [18]:
# inbuild add ufunc
type(np.add)

numpy.ufunc

# Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [19]:
x = np.random.randint(1,10,size=10)
print(x)

[8 4 1 3 3 3 7 3 4 6]


In [20]:
np.where(x == 4)

(array([1, 8]),)

In [21]:
np.where(x>4)

(array([0, 6, 9]),)

# Fast Sorting in NumPy: np.sort and np.argsort

By default np.sort uses an O(N log N)

In [22]:
# np.sort return sorted array
x = np.array([34,2,45,3,2,1,89,54])
np.sort(x)

array([ 1,  2,  2,  3, 34, 45, 54, 89])

In [23]:
# If you prefer to sort the array in-place
x.sort()
x

array([ 1,  2,  2,  3, 34, 45, 54, 89])

# Sorting along rows or columns

A useful feature of NumPy’s sorting algorithms is the ability to sort along specific rows or columns of a multidimensional array using the axis argument

In [24]:
data = np.random.randint(10,100,(10,4))
data

array([[18, 96, 24, 24],
       [49, 75, 83, 83],
       [13, 56, 80, 52],
       [29, 91, 70, 56],
       [25, 36, 80, 15],
       [82, 63, 66, 65],
       [59, 10, 73, 74],
       [97, 77, 64, 35],
       [36, 94, 74, 99],
       [55, 29, 16, 56]])

In [25]:
# Sort each column of data
np.sort(data,axis = 0)

array([[13, 10, 16, 15],
       [18, 29, 24, 24],
       [25, 36, 64, 35],
       [29, 56, 66, 52],
       [36, 63, 70, 56],
       [49, 75, 73, 56],
       [55, 77, 74, 65],
       [59, 91, 80, 74],
       [82, 94, 80, 83],
       [97, 96, 83, 99]])

In [26]:
# Sort each row of data
np.sort(data,axis = 1)

array([[18, 24, 24, 96],
       [49, 75, 83, 83],
       [13, 52, 56, 80],
       [29, 56, 70, 91],
       [15, 25, 36, 80],
       [63, 65, 66, 82],
       [10, 59, 73, 74],
       [35, 64, 77, 97],
       [36, 74, 94, 99],
       [16, 29, 55, 56]])

In [27]:
# Sort Single Column
np.sort(data[:,[1]],axis=0)

array([[10],
       [29],
       [36],
       [56],
       [63],
       [75],
       [77],
       [91],
       [94],
       [96]])

# Filtering Arrays

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

In [28]:
x = np.array([1,2,3,5,6])
f = [True,False,True,True,False]
x[f]

array([1, 3, 5])

In [29]:
x = np.array([1,2,3,5,6])
f = x%2==1
x[f]

array([1, 3, 5])

In [30]:
x = np.array([1,2,3,5,6])
x[x%2==1]

array([1, 3, 5])