<a href="https://colab.research.google.com/github/akdubey/AKDU/blob/main/Lecture_5a_Numpy_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Topics to be covered

* Creating Arrays
* List Vs ndarray
* ndarray Attributes
* Indexing and Slicing

# Introduction to Numpy ![image.png](attachment:image.png)

* NumPy is one of the most important foundational packages for numerical computing in Python.
* It provides a high-performance multidimensional array object, and tools for working with these arrays.


# Import NumPy

In [ ]:
import numpy

Myarray = numpy.array([1,2,3,4])

print(Myarray)

[1 2 3 4]


# NumPy as np

* NumPy is usually imported under the np alias.

> alias: In Python alias are an alternate name for referring to the same thing.

In [ ]:
import numpy as np

Myarray = np.array(['black','blue','green'])

print(Myarray)

['black' 'blue' 'green']


# Checking NumPy Version

In [ ]:
np.__version__

'1.21.6'

# Creating Arrays

* The array object in NumPy is called ndarray.
* We can create a NumPy ndarray object by using the array() function.

# Dimensions in Arrays

* A dimension in arrays is one level of array depth


# 0-D Arrays

In [ ]:
arr = np.array(100)
print(arr)
print(type(arr))

100
<class 'numpy.ndarray'>


# Creating Single-dimensional ndarray


In [ ]:
oneD = np.array([1,2,3,4,5])
print(oneD)

[1 2 3 4 5]


In [ ]:
element = [12,23,34,45,56]
oneD = np.array(element)
print(oneD)

[12 23 34 45 56]


# Creating Multi-dimensional  ndarray

In [ ]:
twoD = np.array([[1,2,3],[4,5,6]])
print(twoD)

[[1 2 3]
 [4 5 6]]


In [ ]:
elem = [[1,2,3,4],[9,8,7,6]]
twoD = np.array(elem)
print(twoD)

[[1 2 3 4]
 [9 8 7 6]]


# Check Dimensions of ndarray

In [ ]:
twoD.ndim

2

In [ ]:
oneD.ndim

1

In [ ]:
threeD = np.array([[[1,2,3],[4,5,6]],[[1,1,1],[2,2,2]]])
threeD.ndim

3

# Creating ndarray with Zeros

In [ ]:
x=np.zeros(5,dtype=int)
x

array([0, 0, 0, 0, 0])

In [ ]:
x= np.zeros((2,3),dtype=float)
x

array([[0., 0., 0.],
       [0., 0., 0.]])

# Creating ndarray with Ones

In [ ]:
x = np.ones(5,dtype=int)
x

array([1, 1, 1, 1, 1])

In [ ]:
x = np.ones((5,5),dtype=int)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Why do we use python numpy if we already have python list?

* We use python numpy array instead of a list because of the below three reasons:

> - Less Memory
> - Fast
> - ConvenientTo understand it

### lets see Example

In [ ]:
# Less Memory

import numpy as np
 
import sys

l = [1,2,3,4,5,6,7,8,9]
print(sys.getsizeof(1)*len(l))

arr = np.array(l)
print(arr.size*arr.itemsize)

252
72


In [ ]:
# Fast 

import numpy as np
import time

l1 = range(1,100000)
l2 = range(1,100000)
A1 = np.array(l1)
A2 = np.array(l2)
start = time.time()
result1 = [x+y for x,y in zip(l1,l2)]
print((time.time()- start)*1000)

start =time.time()
result2 = A1+A2
print((time.time()- start)*1000)

14.071941375732422
0.8289813995361328


# NumPy - Array Attributes ( Array Description)

> #### Each array has features like shape, size and number of dimensions.

# ndarray.shape

>  #### It returns a tuple consisting of array dimensions

In [ ]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a.shape)

(2, 3)


# numpy.itemsize

>  #### Itemsize represents the number of bytes in each element of an array.

In [ ]:
x = np.array([1,2,3,4,5], dtype = np.int8) 
print(x.itemsize)

1


In [ ]:
x = np.array([1,2,3,4,5], dtype = np.float16) 
print(x.itemsize)

2


# How to use Python Numpy to generate Random Numbers?

### The random module in Numpy package contains many functions for generation of random numbers

# 1 .  numpy.random.rand() − 
### Generate Random Float from 0 to 1 of a given size

In [ ]:
# Generate 10 random float
x = np.random.rand(10)
x

array([0.44613944, 0.0622741 , 0.06360678, 0.30892202, 0.87255698,
       0.85627642, 0.51776345, 0.16890137, 0.81764819, 0.50134461])

In [ ]:
# Generate (3X4) vector of random float
x = np.random.rand(3,4)
x

array([[0.08362915, 0.08225417, 0.82110882, 0.20074562],
       [0.86500865, 0.59652253, 0.20952739, 0.41845812],
       [0.23185689, 0.19124872, 0.74258057, 0.98621631]])

# 2. numpy.random.randint() − 
### Generate a random integer from given range ( start to end-1)

In [ ]:
#Generate 10 random integer in between 5 to 10.
x = np.random.randint(5,10,size=10)
x

array([6, 5, 6, 5, 8, 7, 5, 5, 5, 6])

In [ ]:
#Generate (3X2)vector of random integer in between 5 to 10.
x = np.random.randint(5,10,size=(3,2))
x

array([[5, 6],
       [7, 6],
       [8, 9]])

# 3. The choice() method 
### Generate Random Number From Array
### The choice() method allows you to generate a random value based on an array of values.

In [ ]:
# Generate a randome number from a list of element [1,2,3,4,5,6,7,8]
x = np.random.choice([1,2,3,4,5,6,7,8])
x

1

In [ ]:
# The choice() method also allows you to return an array of values.
# Add a size parameter to specify the shape of the array.

x = np.random.choice([1,2,3,4,5,6,7,8],size=2)
x

array([7, 8])

In [ ]:
x = np.random.choice([1,2,3,4,5,6,7,8],size=(2,3))
x

array([[8, 6, 8],
       [2, 8, 1]])

# Accessing elements from an array

> #### Indexing in Numpy is quite similar to Python’s list standard indexing. 


In [ ]:
# In 1-D we can access the nth element by stating the index in square brackets
x = np.array([10,23,45,67,89]) 
x[2]

45

In [ ]:
# Method-1
# In multi dimensional arrays, you can specify a comma separated tuple of indices to access the desired elements.
y = np.array([[12,23,34],[2,4,67]])
y[0,2]

34

In [ ]:
# Method-2
y = np.array([[12,23,34],[2,4,67]])
y[0][2]

34

# Indexing & Slicing

> #### Contents of ndarray object can be accessed and modified by indexing or slicin

# basic slicing

In [ ]:
x = np.array([10,23,45,67,89]) 
x[1:4]

array([23, 45, 67])

In [ ]:
y = np.array([[12,23,34],[2,4,67],[1,1,1],[2,2,2]])
y[1:]

array([[ 2,  4, 67],
       [ 1,  1,  1],
       [ 2,  2,  2]])

In [ ]:
y[-1:]

array([[2, 2, 2]])

In [ ]:
y[-3:-1]

array([[ 2,  4, 67],
       [ 1,  1,  1]])

In [ ]:
y[0:2]

array([[12, 23, 34],
       [ 2,  4, 67]])

In [ ]:
# All item from column 1 onward
y[:,1:]

array([[23, 34],
       [ 4, 67],
       [ 1,  1],
       [ 2,  2]])

In [ ]:
y[0:2,1:]

array([[23, 34],
       [ 4, 67]])

# Boolean Array Indexing

> #### This type of advanced indexing is used when the resultant object is meant to be the result of Boolean operations, such as comparison operators.

In [ ]:
x = np.array([10,23,45,67,89]) 
x[x%5==0]

array([10, 45])

In [ ]:
y = np.array([[12,23,34],[2,4,67],[1,1,1],[2,2,2]])
y[y%2==0]

array([12, 34,  2,  4,  2,  2,  2])

# Fancy Indexing

#### Fancy indexing is like the simple indexing we’ve already seen, but we pass arrays of indices in place of single scalars.

In [ ]:
x = np.random.randint(100,size=(10,6))
x

array([[93, 93, 40,  5, 13, 18],
       [12, 99,  1,  8, 54, 26],
       [96, 76, 33, 88, 79, 54],
       [66, 11, 51, 22, 49, 91],
       [ 1,  9, 91, 63,  2, 39],
       [76, 86, 44, 72, 18, 55],
       [14, 23, 85, 60, 51, 81],
       [31, 67, 19, 24, 26, 36],
       [ 6, 70, 30, 23, 44, 51],
       [99, 65,  5, 38, 23, 56]])

In [ ]:
# print second,forth and sixth column
x[:,[1,3,5]]

array([[93,  5, 18],
       [99,  8, 26],
       [76, 88, 54],
       [11, 22, 91],
       [ 9, 63, 39],
       [86, 72, 55],
       [23, 60, 81],
       [67, 24, 36],
       [70, 23, 51],
       [65, 38, 56]])

In [ ]:
#print from row= 2 to 6
x[1:7,]

array([[12, 99,  1,  8, 54, 26],
       [96, 76, 33, 88, 79, 54],
       [66, 11, 51, 22, 49, 91],
       [ 1,  9, 91, 63,  2, 39],
       [76, 86, 44, 72, 18, 55],
       [14, 23, 85, 60, 51, 81]])

In [ ]:
# print from row= 2 to 6 and only column 4 and 6
x[1:7,[3,5]]

array([[ 8, 26],
       [88, 54],
       [22, 91],
       [63, 39],
       [72, 55],
       [60, 81]])

In [ ]:
# More about Indexing
print(x)
x[2:5]

[[93 93 40  5 13 18]
 [12 99  1  8 54 26]
 [96 76 33 88 79 54]
 [66 11 51 22 49 91]
 [ 1  9 91 63  2 39]
 [76 86 44 72 18 55]
 [14 23 85 60 51 81]
 [31 67 19 24 26 36]
 [ 6 70 30 23 44 51]
 [99 65  5 38 23 56]]


array([[96, 76, 33, 88, 79, 54],
       [66, 11, 51, 22, 49, 91],
       [ 1,  9, 91, 63,  2, 39]])

In [ ]:
x[2:5][0] # It gives first row

array([96, 76, 33, 88, 79, 54])

In [ ]:
x[2:5][:,3:] # it gives col 3 to end

array([[88, 79, 54],
       [22, 49, 91],
       [63,  2, 39]])